### ISSUE TITLE
Readme has wrong methodname for ecs.render()

### ISSUE THREAD

**Issue by ineptech** [andyhall/ent-comp#1]
// calling tick/render triggers the systems
    ecs.tick( tick_time )
    ecs.tickRender( render_time )

s/tickRender/render

**Comment by andyhall** [comment]
Thanks! Want to submit a PR?

**Comment by ineptech** [comment]
If I actually add anything I will. I've got an idea for that actually, not
sure if I'll have time to implement it...

**Comment by andyhall** [comment]
Too late. Let me know what you're interested in adding, please, or what you think is missing!

**Comment by ineptech** [comment]
I was thinking of expiring components.




ecs.createComponent({
    name: 'isSwingingSword',
    state: { },
    onRemove: function(id, state) {
        ecs.addComponent(id, 'canAttack');
    },
    expiry: 500
});
ecs.addComponent(id, 'isSwingingSword');
ecs.tick(100);
ecs.hasComponent(id, 'isSwingingSword');  // true
ecs.getState(id, 'isSwingingSowrd').expiry;  // 400
ecs.tick(401);
ecs.hasComponent(id, 'isSwingingSword');  // false
ecs.hasComponent(id, 'canAttack');  //true

Would be useful for short-lived things like attack animation, where you
need to know the time-remaining but otherwise don't have anything to put in
system().  Not hard for the user to do themselves, but seems like it'd be
so common a use case that simplifying it would be a nice addition.  Not
sure if it should key off of of system time or render time, or both
(meaning, have expiry and expiryRender).  Whatcha think?

**Comment by ineptech** [comment]
Does no response mean it's such a great idea you are implementing it now,
such a bad idea you can't bear to discuss it, or such a mediocre idea you
got drunk and forgot?  I didn't put any work in to it this weekend but I'm
fiddling with a "move around and shoot little things" pseudogame in the
browser using ecs.

**Comment by andyhall** [comment]
Well, I haven't thought deeply but my first reaction is that something like that might be better left in client code? Unless there's a reason why it's better done inside the library than out (e.g. it needed to mess with internal data structures).

**Comment by ineptech** [comment]
http://codepen.io/cheryllium/pen/JXeaBp  <-- UX progress marches onward
