### ISSUE TITLE
Add systems and storage back to the object prototype?

### ISSUE THREAD

**Issue by PandawanFr** [andyhall/ent-comp#3]
I've been using the `noa` package for a while and recently decided to switch to using a fork so I could update the dependencies. When I updated `ent-comp`, it seems that `storage`,  `systems` and `renderSystems` are no longer accessible from the outside.

I'm mostly using it to quickly check states of different entities in the Chrome console, which is much faster than having to use the API calls for every single component type. ([I simply type `noa` in the console and have access to everything](https://i.imgur.com/o0oy7f7.png)).

So I was wondering if you could possibly add them back to the object through `this.storage`, etc. (seeing that `this.components` is still available) or provide another way to quickly get all of this data.

**Comment by andyhall** [comment]
Hi, sure I can restore this! Those are meant to be "internal" references, that might change in the future etc., so maybe I should make them `ents._storage`, `ents._systems` etc. But I can put the references back, and push a build today or tomorrow.

By the way, if you'd like to use newest `noa` that already has updated dependency versions, you can also clone the noa repo and have your project import from the `develop` branch. Usually when I update noa's dependencies it's for the sake of something I'm doing in that branch, so I'll push a new version of ent-comp and update the dependency in `noa#develop` at the same time. But then I try to wait a little while before pulling the changes into `noa#master`, to avoid having it get too volatile.

**Comment by PandawanFr** [comment]
Thanks, that’d be great! 

And yeah I considered doing that too but I decided to go with a fork + git submodules so I could separate the project from the engine a bit. I ended up updating noa to ES6+ (with [lebab](https://github.com/lebab/lebab)) and modifying a bunch of stuff for my personal usage. Thanks tho!

**Comment by andyhall** [comment]
This should be published now as `0.9.1`. I'll up the dependency on noa's side in the next update. Thanks!
